name: seed_flutter
description: "Seed Flutter Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Environment
  flutter_dotenv: ^5.1.0

  #State Management
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5

  #Service
  dio: ^5.4.3+1
  jwt_decoder: ^2.0.1

  #Intl
  intl: ^0.19.0

  # Url Launcher
  url_launcher: ^6.3.0
  mailto: ^2.0.0

  #Shimmer
  shimmer: ^3.0.0

  # Network Image
  cached_network_image: ^3.3.1

  #Device Info
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  share_plus: ^9.0.0
  safe_device: ^1.1.7
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # Assets
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1

  # Toast
  bot_toast: ^4.1.3

  # File
  image_picker: ^1.1.2

  #Shared Preference
  encrypt: ^5.0.3
  shared_preferences: ^2.2.3

  #Routing
  go_router: ^14.1.4

  #Kanban Board
  appflowy_board: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/animation/
    - .env.dev
    - .env.stage
    - .env.prod
    - .env.qa

